# -*- coding: utf-8 -*-
"""5program.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hKt6L3Xq-TdKdVI7A_rcIjGaCEWd9cFZ
"""

pip install sentence_transformers

from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('all-MiniLM-L6-v2')
corpus = [
"The stock market saw significant gains today, driven by strongearnings reports.",
"Investing in diversified portfolios helps mitigate risk andmaximize returns.",
"The Federal Reserve's decision to raise interest rates couldimpact market liquidity.",
"Cryptocurrency has become an increasingly popular asset classamong investors.",
"Financial analysts predict that the global economy will facechallenges in the coming years.",
"Bonds are considered a safer investment option compared tostocks.",
"Banks are adopting blockchain technology to improve the efficiencyof financial transactions.",
"The economic impact of the pandemic has been severe, but recoveryis underway.",
"Inflation rates have been rising steadily, leading to higher costsfor consumers.",
"Corporate governance and transparency are crucial for investorconfidence.",
"The real estate market is experiencing a boom as demand outstripssupply in many areas.",
]
corpus_embeddings = model.encode(corpus, convert_to_tensor=True)
corpus_embeddings

def generate_paragraph(seed_word, corpus, corpus_embeddings, model,top_n=5):
  seed_sentence = f"Tell me more about {seed_word} in finance."
  seed_embedding = model.encode(seed_sentence,convert_to_tensor=True)
  similarities = util.pytorch_cos_sim(seed_embedding,corpus_embeddings)[0]
  top_results = similarities.topk(top_n)
  print('top_results:',top_results)
  story = f"The topic of '{seed_word}' is crucial in the finance industry. "
  for idx in top_results.indices:
      similar_sentence = corpus[idx]
      story += f"{similar_sentence} "
      story += f"These concepts highlight the importance of {seed_word} in understanding financial markets and investment strategies."
  return story
seed_word = "bonds"
story = generate_paragraph(seed_word, corpus, corpus_embeddings, model,top_n=5)
print(story)

!pip install langchain-huggingface
!pip install tf-keras --user
!pip install numpy==1.24.4 --user