# -*- coding: utf-8 -*-
"""Prg 2 and 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MoA4nhbTIs0zwZxAfdlxsywMIPEDcWwO
"""

!pip install gensim

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from gensim.models import KeyedVectors
import numpy as np

# Load the GloVe model with no_header=True
model_100d = KeyedVectors.load_word2vec_format("/content/drive/MyDrive/Gen AI/glove.6B.100d.txt", binary=False, limit=500000, no_header=True)

words = ['football', 'soccer', 'basketball', 'tennis', 'engineer', 'information', 'baseball', 'coach', 'goal', 'player', 'referee', 'team']
word_vectors = np.array([model_100d[word] for word in words])

pca = PCA(n_components=2)
pca_result = pca.fit_transform(word_vectors)

plt.figure(figsize=(10, 8))
for i, word in enumerate(words):
    plt.scatter(pca_result[i, 0], pca_result[i, 1])
    plt.text(pca_result[i, 0] + 0.02, pca_result[i, 1], word, fontsize=12)

plt.title("PCA Visualization of Sports-related Word Embeddings (100d)")
plt.xlabel("PCA Dimension 1")
plt.ylabel("PCA Dimension 2")
plt.show()  # Moved plt.show() outside the loop


def get_similar_words(word, model, topn=5):
    similar_words = model.similar_by_word(word, topn=topn)
    return similar_words

# Call the function and print the results (unindented)
similar_words_football = get_similar_words('football', model_100d, topn=5)
print(f"Words similar to 'football': {similar_words_football}")

!pip install gensim

from gensim.models import Word2Vec
from gensim.utils import simple_preprocess
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

legal_corpus = [
"The court ruled in favor of the plaintiff.",
"The defendant was found guilty of negligence.",
"A breach of contract case was filed.",
"The agreement between parties must be honored.",
"The lawyer presented compelling evidence.",
"Legal documents must be drafted carefully.",
"The jury deliberated for several hours.",
"A settlement was reached between the parties.",
"The plaintiff claimed damages for losses incurred.",
"The contract outlined the obligations of both parties."
]

tokenized_corpus = [simple_preprocess(sentence) for sentence in legal_corpus]
legal_word2vec = Word2Vec(sentences=tokenized_corpus,vector_size=50, window=3,min_count=1, sg=1,epochs=100)
legal_word2vec.save("legal_word2vec.model")
word = "lawyer"
if word in legal_word2vec.wv:
  print(f"Vector embedding for'{word}':\n{legal_word2vec.wv[word]}\n")
else:
  print(f"Word '{word}' not found in the Word2Vec model.")

words_to_visualize = ["court", "plaintiff", "defendant", "agreement","lawyer", "evidence", "contract", "settlement", "jury", "damages"]
word_vectors = [legal_word2vec.wv[word] for word in words_to_visualize]
word_vectors

pca = PCA(n_components=2)
reduced_vectors = pca.fit_transform(word_vectors)
reduced_vectors

plt.figure(figsize=(10, 8))
for i, word in enumerate(selected_words):  # Changed words_to_visualize to selected_words
    plt.scatter(reduced_vectors[i, 0], reduced_vectors[i, 1])
    plt.text(reduced_vectors[i, 0] + 0.002, reduced_vectors[i, 1], word, fontsize=12)
    plt.title("PCA Visualization of Legal Word Embeddings")
plt.xlabel("PCA Dimension 1")
plt.ylabel("PCA Dimension 2")
plt.show()

similar_words = legal_word2vec.wv.most_similar("lawyer", topn=5)
print(f"Words similar to 'lawyer': {similar_words}")

from gensim.models import Word2Vec
from gensim.utils import simple_preprocess
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# Enhanced legal and medical corpus
enhanced_corpus = [
    # Legal domain
    "The court ordered the immediate release of the detained individual due to lack of evidence.",
    "A new amendment was introduced to ensure the protection of intellectual property rights.",
    "The defendant pleaded not guilty, citing an alibi supported by credible witnesses.",
    "The plaintiff accused the company of violating environmental regulations.",
    "A settlement agreement was reached through arbitration, avoiding a lengthy trial.",
    "The legal team presented a compelling argument to overturn the previous judgment.",
    "Contractual obligations must be fulfilled unless waived by mutual consent.",
    "The jury found the accused guilty of fraud and embezzlement.",
    "The appeal was dismissed as the evidence presented was deemed inadmissible.",
    "The attorney emphasized the importance of adhering to constitutional rights.",
    # Medical domain
    "The patient was admitted to the emergency department with severe chest pain.",
    "The surgeon successfully performed a minimally invasive procedure to remove the tumor.",
    "Clinical trials showed significant improvement in patients treated with the experimental drug.",
    "Regular screening is essential for early detection of chronic illnesses such as diabetes.",
    "The doctor recommended physical therapy to improve mobility after surgery.",
    "The hospital implemented stringent protocols to prevent the spread of infectious diseases.",
    "The nurse monitored the patient's vital signs hourly to ensure stability.",
    "Vaccination campaigns have drastically reduced the prevalence of polio worldwide.",
    "The radiologist identified a small abnormality in the CT scan requiring further investigation.",
    "Proper nutrition and exercise are vital components of a healthy lifestyle."
]
tokenized_corpus = [simple_preprocess(sentence) for sentence in
enhanced_corpus]
tokenized_corpus

domain_word2vec = Word2Vec(sentences=tokenized_corpus,vector_size=100, window=5,
min_count=1,sg=1,epochs=150)
domain_word2vec.save("enhanced_domain_word2vec.model")
words_to_analyze = ["court", "plaintiff", "doctor", "patient","guilty", "surgery"]
for word in words_to_analyze:
  if word in domain_word2vec.wv:
    print(f"Vector embedding for'{word}':\n{domain_word2vec.wv[word]}\n")
  else:
    print(f"Word '{word}' not found in the Word2Vec model.")

selected_words = ["court", "plaintiff", "defendant", "guilty", "jury","patient", "doctor", "hospital", "surgery","emergency"]
word_vectors = [domain_word2vec.wv[word] for word in selected_words]
word_vectors

pca = PCA(n_components=2)
reduced_vectors = pca.fit_transform(word_vectors)
reduced_vectors

plt.figure(figsize=(12, 8))
for i, word in enumerate(selected_words):
  plt.scatter(reduced_vectors[i, 0], reduced_vectors[i, 1])
  plt.text(reduced_vectors[i, 0] + 0.002, reduced_vectors[i, 1],word, fontsize=12)
plt.title("PCA Visualization of Legal and Medical Word Embeddings")
plt.xlabel("PCA Dimension 1")
plt.ylabel("PCA Dimension 2")
plt.show()